shfmt with more tsish settings

diff --git a/bin/vimv b/bin/vimv
--- a/bin/vimv
+++ b/bin/vimv
@@ -10,13 +10,13 @@ FILENAMES_FILE=$(mktemp "${TMPDIR:-/tmp}/vimv.XXXXXX")
 trap '{ rm -f "${FILENAMES_FILE}" ; }' EXIT
 
 if [ $# -ne 0 ]; then
-	src=("$@")
+  src=("$@")
 else
-	IFS=$'\r\n' GLOBIGNORE='*' command eval 'src=($(ls))'
+  IFS=$'\r\n' GLOBIGNORE='*' command eval 'src=($(ls))'
 fi
 
 for ((i = 0; i < ${#src[@]}; ++i)); do
-	echo "${src[i]}" >>"${FILENAMES_FILE}"
+  echo "${src[i]}" >> "${FILENAMES_FILE}"
 done
 
 ${EDITOR:-vi} "${FILENAMES_FILE}"
@@ -25,21 +25,21 @@ IFS=$'\r\n' GLOBIGNORE='*' command eval 'dest=($(cat "${FILENAMES_FILE}"))'
 
 # shellcheck disable=SC2154
 if ((${#src[@]} != ${#dest[@]})); then
-	echo "WARN: Number of files changed. Did you delete a line by accident? Aborting.." >&2
-	exit 1
+  echo "WARN: Number of files changed. Did you delete a line by accident? Aborting.." >&2
+  exit 1
 fi
 
 declare -i count=0
 for ((i = 0; i < ${#src[@]}; ++i)); do
-	if [ "${src[i]}" != "${dest[i]}" ]; then
-		mkdir -p "$(dirname "${dest[i]}")"
-		if git ls-files --error-unmatch "${src[i]}" >/dev/null 2>&1; then
-			git mv -- "${src[i]}" "${dest[i]}"
-		else
-			mv -- "${src[i]}" "${dest[i]}"
-		fi
-		((++count))
-	fi
+  if [ "${src[i]}" != "${dest[i]}" ]; then
+    mkdir -p "$(dirname "${dest[i]}")"
+    if git ls-files --error-unmatch "${src[i]}" > /dev/null 2>&1; then
+      git mv -- "${src[i]}" "${dest[i]}"
+    else
+      mv -- "${src[i]}" "${dest[i]}"
+    fi
+    ((++count))
+  fi
 done
 
 echo "$count" files renamed.
